$schema: ./schema.json
# Native
App:
  Landscape: lapras
  EnableSwagger: true
  GenerateConfig: true
Swagger:
  Title: Lapras Nitroso Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: false
Trace:
  Exporter:
    Otlp:
      Enabled: false

Metrics:
  Exporter:
    Otlp:
      Enabled: false

# Infra-based
Database:
  MAIN:
    Host: zinc-maindb
    User: admin
    Password: supersecret
    AutoMigrate: true

Cache:
  MAIN:
    Endpoints:
      - zinc-maincache:6379
    Password: supersecret
  STREAM:
    Endpoints:
      - zinc-streamcache:6379
    Password: supersecret
BlockStorage:
  MAIN:
    Read:
      Host: mainstorage.zinc.nitroso.lapras.lvh.me
      Port: 20010
      Scheme: http
    Write:
      Host: zinc-mainstorage
      Port: 9000
      Scheme: http
    Policy: Private
    UseSSL: false
    EnsureBucketCreation: true
# external
HttpClient: {}
