// <auto-generated />
using System;
using System.Collections.Generic;
using App.StartUp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240112032654_Withdrawal")]
    partial class Withdrawal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Modules.Bookings.Data.BookingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Ticket")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ComplexProperty<Dictionary<string, object>>("Passenger", "App.Modules.Bookings.Data.BookingData.Passenger#BookingPassengerData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<byte>("Gender")
                                .HasColumnType("smallint");

                            b1.Property<DateOnly>("PassportExpiry")
                                .HasColumnType("date");

                            b1.Property<string>("PassportNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("App.Modules.Passengers.Data.PassengerData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("PassportExpiry")
                        .HasColumnType("date");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("App.Modules.Schedules.Data.ScheduleData", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly[]>("JToWExcluded")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.Property<TimeOnly[]>("WToJExcluded")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.HasKey("Date");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("App.Modules.Timings.Data.TimingData", b =>
                {
                    b.Property<int>("Direction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Direction"));

                    b.Property<TimeOnly[]>("Timings")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.HasKey("Direction");

                    b.ToTable("Timings");

                    b.HasData(
                        new
                        {
                            Direction = 1,
                            Timings = new[] { new TimeOnly(5, 0, 0), new TimeOnly(5, 30, 0), new TimeOnly(6, 0, 0), new TimeOnly(6, 30, 0), new TimeOnly(7, 0, 0), new TimeOnly(7, 30, 0), new TimeOnly(8, 45, 0), new TimeOnly(10, 0, 0), new TimeOnly(11, 30, 0), new TimeOnly(12, 45, 0), new TimeOnly(14, 0, 0), new TimeOnly(15, 15, 0), new TimeOnly(16, 30, 0), new TimeOnly(17, 45, 0), new TimeOnly(19, 0, 0), new TimeOnly(20, 15, 0), new TimeOnly(21, 30, 0), new TimeOnly(22, 45, 0) }
                        },
                        new
                        {
                            Direction = 2,
                            Timings = new[] { new TimeOnly(8, 30, 0), new TimeOnly(9, 45, 0), new TimeOnly(11, 0, 0), new TimeOnly(12, 30, 0), new TimeOnly(13, 45, 0), new TimeOnly(15, 0, 0), new TimeOnly(16, 15, 0), new TimeOnly(17, 30, 0), new TimeOnly(18, 45, 0), new TimeOnly(20, 0, 0), new TimeOnly(21, 15, 0), new TimeOnly(22, 30, 0), new TimeOnly(23, 45, 0) }
                        });
                });

            modelBuilder.Entity("App.Modules.Transactions.Data.TransactionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("App.Modules.Users.Data.UserData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.Modules.Wallets.Data.WalletData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BookingReserve")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<decimal>("Usable")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("WithdrawReserve")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompleterId")
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("PayNowNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Receipt")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompleterId");

                    b.HasIndex("WalletId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.BookingData", b =>
                {
                    b.HasOne("App.Modules.Transactions.Data.TransactionData", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Modules.Users.Data.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Passengers.Data.PassengerData", b =>
                {
                    b.HasOne("App.Modules.Users.Data.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Transactions.Data.TransactionData", b =>
                {
                    b.HasOne("App.Modules.Wallets.Data.WalletData", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("App.Modules.Wallets.Data.WalletData", b =>
                {
                    b.HasOne("App.Modules.Users.Data.UserData", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("App.Modules.Wallets.Data.WalletData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalData", b =>
                {
                    b.HasOne("App.Modules.Users.Data.UserData", "Completer")
                        .WithMany()
                        .HasForeignKey("CompleterId");

                    b.HasOne("App.Modules.Wallets.Data.WalletData", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Completer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("App.Modules.Users.Data.UserData", b =>
                {
                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
