// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using App.StartUp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260713210128_AddPriorityPoliciesAndSlotCap")]
    partial class AddPriorityPoliciesAndSlotCap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Modules.Bookings.Data.BookingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingNo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastBuyingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PrioritizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrioritizedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Priority")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriorityFee")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<int>("RecoveryRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Times this booking was recycled from Recovering back to Pending (RecoverRevert); capped by Recovery:MaxRetries");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Ticket")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TicketNo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ComplexProperty<Dictionary<string, object>>("Passenger", "App.Modules.Bookings.Data.BookingData.Passenger#BookingPassengerData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<byte>("Gender")
                                .HasColumnType("smallint");

                            b1.Property<DateOnly>("PassportExpiry")
                                .HasColumnType("date");

                            b1.Property<string>("PassportNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.BookingStatData", b =>
                {
                    b.Property<int>("Cancelled")
                        .HasColumnType("integer");

                    b.Property<int>("Completed")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DemandBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("LeadBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Other")
                        .HasColumnType("integer");

                    b.Property<bool>("Priority")
                        .HasColumnType("boolean");

                    b.Property<int>("Refunded")
                        .HasColumnType("integer");

                    b.Property<int>("Terminated")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("booking_stats", (string)null);
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.KtmbCostData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Direction", "EffectiveAt");

                    b.ToTable("KtmbCosts");
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.PriorityAccessData", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("PriorityAccesses");
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.PrioritySettingsData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAll")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fee")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<int?>("SlotCap")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("WindowEndSgt")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("WindowStartSgt")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("PrioritySettings");
                });

            modelBuilder.Entity("App.Modules.Costs.Data.CostData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsUnique();

                    b.ToTable("Costs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6dfd5a2b-37a0-4c65-9d05-1c8dbd5237a2"),
                            Cost = 14m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("App.Modules.Costs.Data.CostPolicyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeadTimeUnderHours")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("MatchDate")
                        .HasColumnType("date");

                    b.Property<byte?>("MatchDayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<int?>("MatchDirection")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("MatchTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("CostPolicies");
                });

            modelBuilder.Entity("App.Modules.Discounts.Data.DiscountData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LeadTimeAtLeastHours")
                        .HasColumnType("integer")
                        .HasColumnName("LeadTimeUnderHours");

                    b.Property<DateOnly?>("MatchDate")
                        .HasColumnType("date");

                    b.Property<byte?>("MatchDayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<int?>("MatchDirection")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("MatchTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("App.Modules.Milestones.Data.MilestoneData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("App.Modules.Passengers.Data.PassengerData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("PassportExpiry")
                        .HasColumnType("date");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("App.Modules.Payments.Data.GatewayFeeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<string>("FinancialTransactionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Net")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TransactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FinancialTransactionId")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.HasIndex("TransactedAt");

                    b.ToTable("GatewayFees");
                });

            modelBuilder.Entity("App.Modules.Payments.Data.PaymentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<decimal>("CapturedAmount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference");

                    b.HasIndex("WalletId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("App.Modules.Schedules.Data.ScheduleData", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly[]>("JToWExcluded")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.Property<TimeOnly[]>("WToJExcluded")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.HasKey("Date");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("App.Modules.Timings.Data.TimingData", b =>
                {
                    b.Property<int>("Direction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Direction"));

                    b.Property<TimeOnly[]>("Timings")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.HasKey("Direction");

                    b.ToTable("Timings");

                    b.HasData(
                        new
                        {
                            Direction = 1,
                            Timings = new[] { new TimeOnly(5, 0, 0), new TimeOnly(5, 30, 0), new TimeOnly(6, 0, 0), new TimeOnly(6, 30, 0), new TimeOnly(7, 0, 0), new TimeOnly(7, 30, 0), new TimeOnly(8, 45, 0), new TimeOnly(10, 0, 0), new TimeOnly(11, 30, 0), new TimeOnly(12, 45, 0), new TimeOnly(14, 0, 0), new TimeOnly(15, 15, 0), new TimeOnly(16, 30, 0), new TimeOnly(17, 45, 0), new TimeOnly(19, 0, 0), new TimeOnly(20, 15, 0), new TimeOnly(21, 30, 0), new TimeOnly(22, 45, 0) }
                        },
                        new
                        {
                            Direction = 2,
                            Timings = new[] { new TimeOnly(8, 30, 0), new TimeOnly(9, 45, 0), new TimeOnly(11, 0, 0), new TimeOnly(12, 30, 0), new TimeOnly(13, 45, 0), new TimeOnly(15, 0, 0), new TimeOnly(16, 15, 0), new TimeOnly(17, 30, 0), new TimeOnly(18, 45, 0), new TimeOnly(20, 0, 0), new TimeOnly(21, 15, 0), new TimeOnly(22, 30, 0), new TimeOnly(23, 45, 0) }
                        });
                });

            modelBuilder.Entity("App.Modules.Transactions.Data.TransactionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("App.Modules.Users.Data.UserData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string[]>("ExtraRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string[]>("Roles")
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.Modules.Wallets.Data.WalletData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BookingReserve")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<decimal>("Usable")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("WithdrawReserve")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.FeeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cap")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FlatAmount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompleterId")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Fee")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<byte>("Method")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasComment("Payout rail: 0 = PayNow transfer, 1 = card refunds (Airwallex)");

                    b.Property<string>("Note")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("PayNowNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PayoutAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("Receipt")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ReconcileAttempts")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompleterId");

                    b.HasIndex("WalletId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalRefundData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AirwallexRefundId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("WithdrawalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("WithdrawalId");

                    b.ToTable("WithdrawalRefunds");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalSettingsData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CardRefundEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("PayNowMode")
                        .HasColumnType("smallint");

                    b.Property<bool>("SweepEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("WithdrawalSettings");
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.BookingData", b =>
                {
                    b.HasOne("App.Modules.Transactions.Data.TransactionData", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Modules.Users.Data.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("App.Modules.Bookings.Data.BookingPriceBreakdownData", "PriceBreakdown", b1 =>
                        {
                            b1.Property<Guid>("BookingDataId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BaseCost")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Final")
                                .HasColumnType("numeric");

                            b1.HasKey("BookingDataId");

                            b1.ToTable("Bookings");

                            b1.ToJson("PriceBreakdown");

                            b1.WithOwner()
                                .HasForeignKey("BookingDataId");

                            b1.OwnsMany("App.Modules.Bookings.Data.BookingPriceLineData", "Lines", b2 =>
                                {
                                    b2.Property<Guid>("BookingPriceBreakdownDataBookingDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Delta")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("BookingPriceBreakdownDataBookingDataId", "Id");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingPriceBreakdownDataBookingDataId");
                                });

                            b1.Navigation("Lines");
                        });

                    b.Navigation("PriceBreakdown");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Bookings.Data.PrioritySettingsData", b =>
                {
                    b.OwnsMany("App.Modules.Bookings.Data.PriorityPolicyData", "Policies", b1 =>
                        {
                            b1.Property<Guid>("PrioritySettingsDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<bool>("Allow")
                                .HasColumnType("boolean");

                            b1.Property<decimal?>("FeeOverride")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("MaxHoursToDeparture")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("MinHoursToDeparture")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PrioritySettingsDataId", "Id");

                            b1.ToTable("PrioritySettings");

                            b1.ToJson("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PrioritySettingsDataId");

                            b1.OwnsOne("App.Modules.Discounts.Data.DiscountTargetData", "Target", b2 =>
                                {
                                    b2.Property<Guid>("PriorityPolicyDataPrioritySettingsDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PriorityPolicyDataId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("MatchMode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PriorityPolicyDataPrioritySettingsDataId", "PriorityPolicyDataId");

                                    b2.ToTable("PrioritySettings");

                                    b2.WithOwner()
                                        .HasForeignKey("PriorityPolicyDataPrioritySettingsDataId", "PriorityPolicyDataId");

                                    b2.OwnsMany("App.Modules.Discounts.Data.DiscountMatchData", "Matches", b3 =>
                                        {
                                            b3.Property<Guid>("DiscountTargetDataPriorityPolicyDataPrioritySettingsDataId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("DiscountTargetDataPriorityPolicyDataId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<string>("Type")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("DiscountTargetDataPriorityPolicyDataPrioritySettingsDataId", "DiscountTargetDataPriorityPolicyDataId", "Id");

                                            b3.ToTable("PrioritySettings");

                                            b3.WithOwner()
                                                .HasForeignKey("DiscountTargetDataPriorityPolicyDataPrioritySettingsDataId", "DiscountTargetDataPriorityPolicyDataId");
                                        });

                                    b2.Navigation("Matches");
                                });

                            b1.Navigation("Target");
                        });

                    b.OwnsOne("App.Modules.Discounts.Data.DiscountTargetData", "AccessTarget", b1 =>
                        {
                            b1.Property<Guid>("PrioritySettingsDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MatchMode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PrioritySettingsDataId");

                            b1.ToTable("PrioritySettings");

                            b1.ToJson("AccessTarget");

                            b1.WithOwner()
                                .HasForeignKey("PrioritySettingsDataId");

                            b1.OwnsMany("App.Modules.Discounts.Data.DiscountMatchData", "Matches", b2 =>
                                {
                                    b2.Property<Guid>("DiscountTargetDataPrioritySettingsDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DiscountTargetDataPrioritySettingsDataId", "Id");

                                    b2.ToTable("PrioritySettings");

                                    b2.WithOwner()
                                        .HasForeignKey("DiscountTargetDataPrioritySettingsDataId");
                                });

                            b1.Navigation("Matches");
                        });

                    b.OwnsOne("App.Modules.Discounts.Data.DiscountTargetData", "FreeTarget", b1 =>
                        {
                            b1.Property<Guid>("PrioritySettingsDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MatchMode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PrioritySettingsDataId");

                            b1.ToTable("PrioritySettings");

                            b1.ToJson("FreeTarget");

                            b1.WithOwner()
                                .HasForeignKey("PrioritySettingsDataId");

                            b1.OwnsMany("App.Modules.Discounts.Data.DiscountMatchData", "Matches", b2 =>
                                {
                                    b2.Property<Guid>("DiscountTargetDataPrioritySettingsDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DiscountTargetDataPrioritySettingsDataId", "Id");

                                    b2.ToTable("PrioritySettings");

                                    b2.WithOwner()
                                        .HasForeignKey("DiscountTargetDataPrioritySettingsDataId");
                                });

                            b1.Navigation("Matches");
                        });

                    b.Navigation("AccessTarget");

                    b.Navigation("FreeTarget");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("App.Modules.Discounts.Data.DiscountData", b =>
                {
                    b.OwnsOne("App.Modules.Discounts.Data.DiscountTargetData", "Target", b1 =>
                        {
                            b1.Property<Guid>("DiscountDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MatchMode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DiscountDataId");

                            b1.ToTable("Discounts");

                            b1.ToJson("Target");

                            b1.WithOwner()
                                .HasForeignKey("DiscountDataId");

                            b1.OwnsMany("App.Modules.Discounts.Data.DiscountMatchData", "Matches", b2 =>
                                {
                                    b2.Property<Guid>("DiscountTargetDataDiscountDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DiscountTargetDataDiscountDataId", "Id");

                                    b2.ToTable("Discounts");

                                    b2.WithOwner()
                                        .HasForeignKey("DiscountTargetDataDiscountDataId");
                                });

                            b1.Navigation("Matches");
                        });

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Modules.Passengers.Data.PassengerData", b =>
                {
                    b.HasOne("App.Modules.Users.Data.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Payments.Data.PaymentData", b =>
                {
                    b.HasOne("App.Modules.Wallets.Data.WalletData", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("App.Modules.Payments.Data.PaymentStatusData", "Statuses", b1 =>
                        {
                            b1.Property<Guid>("PaymentDataId")
                                .HasColumnType("uuid");

                            b1.HasKey("PaymentDataId");

                            b1.ToTable("Payments");

                            b1.ToJson("Statuses");

                            b1.WithOwner()
                                .HasForeignKey("PaymentDataId");

                            b1.OwnsMany("App.Modules.Payments.Data.PaymentStatusEntryData", "Statuses", b2 =>
                                {
                                    b2.Property<Guid>("PaymentStatusDataPaymentDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("Updated")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("PaymentStatusDataPaymentDataId", "Id");

                                    b2.ToTable("Payments");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentStatusDataPaymentDataId");
                                });

                            b1.Navigation("Statuses");
                        });

                    b.Navigation("Statuses")
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("App.Modules.Transactions.Data.TransactionData", b =>
                {
                    b.HasOne("App.Modules.Payments.Data.PaymentData", "Payment")
                        .WithOne("Transaction")
                        .HasForeignKey("App.Modules.Transactions.Data.TransactionData", "PaymentId");

                    b.HasOne("App.Modules.Wallets.Data.WalletData", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("App.Modules.Wallets.Data.WalletData", b =>
                {
                    b.HasOne("App.Modules.Users.Data.UserData", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("App.Modules.Wallets.Data.WalletData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalData", b =>
                {
                    b.HasOne("App.Modules.Users.Data.UserData", "Completer")
                        .WithMany()
                        .HasForeignKey("CompleterId");

                    b.HasOne("App.Modules.Wallets.Data.WalletData", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Completer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalRefundData", b =>
                {
                    b.HasOne("App.Modules.Payments.Data.PaymentData", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Modules.Withdrawals.Data.WithdrawalData", "Withdrawal")
                        .WithMany("Refunds")
                        .HasForeignKey("WithdrawalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Withdrawal");
                });

            modelBuilder.Entity("App.Modules.Payments.Data.PaymentData", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("App.Modules.Users.Data.UserData", b =>
                {
                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("App.Modules.Withdrawals.Data.WithdrawalData", b =>
                {
                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
