serviceTree:
  landscape: &landscape tauros

bromine:
  enable: true
  serviceTree:
    landscape: *landscape

api:
  enabled: true

  fullnameOverride: 'zinc-api'
  serviceTree:
    landscape: *landscape

  imagePullSecrets: []

  replicaCount: 1

  configMountPath: /app/Config

  service:
    type: ClusterIP
    port: 80
    containerPort: 9030

  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: api.zinc.nitroso.tauros.lvh.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

migration:
  enabled: true
  fullnameOverride: 'zinc-migration'
  serviceTree:
    landscape: *landscape

maindb:
  enable: true
  fullnameOverride: 'zinc-maindb'

maincache:
  enable: true
  fullnameOverride: 'zinc-maincache'

mainstorage:
  enable: true
  fullnameOverride: 'zinc-mainstorage'
