serviceTree: &serviceTree
  landscape: lapras
  platform: nitroso
  service: zinc
  layer: "2"

bromine:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  enable: false
  # -- Store name to create
  storeName: nitroso-zinc
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "NITROSO_ZINC"

  target: &target "nitroso-zinc"

api:
  enabled: true
  annotations:
    argocd.argoproj.io/sync-wave: "4"

  nameOverride: "zinc-api"

  envFromSecret: *target

  serviceTree:
    <<: *serviceTree
    module: api

  imagePullSecrets: []

  replicaCount: 1

  appSettings:
    App:
      Mode: Server

  configMountPath: /app/Config

  image:
    repository: nitroso-zinc-api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80
    containerPort: 9000

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: api.zinc.nitroso.lapras.lvh.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: sample
        issuerRef: sample
        hosts:
          - api.zinc.nitroso.lapras.lvh.me

  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling: {}
  readinessProbe:
    httpGet:
      path: /
      port: http

  livenessProbe:
    httpGet:
      path: /
      port: http

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: {}

migration:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  enabled: false

  nameOverride: "zinc-migration"

  envFromSecret: *target

  serviceTree:
    <<: *serviceTree
    module: migration
  aspNetEnv: Development

  appSettings:
    App:
      Mode: Migration

  backoffLimit: 4

  configMountPath: /app/Config

  image:
    repository: nitroso-zinc-migration
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: {}

maindb:
  nameOverride: zinc-maindb
  primary:
    persistence:
      enabled: false
  auth:
    database: nitroso-zinc
    username: admin
    password: supersecret

mainstorage:
  nameOverride: zinc-mainstorage
  persistence:
    enabled: false
    size: 10Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: console-mainstorage.zinc.nitroso.lapras.lvh.me
  apiIngress:
    enabled: true
    ingressClassName: traefik
    hostname: mainstorage.zinc.nitroso.lapras.lvh.me
  auth:
    rootUser: admin
    rootPassword: supersecret
