$schema: ./schema.json
# Native
App:
  Landscape: raichu
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Raichu Nitroso Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: true
Trace:
  Exporter:
    Otlp:
      Enabled: true

Metrics:
  Exporter:
    Otlp:
      Enabled: true

# Infra-based
Smtp:
  TRANSACTIONAL:
    Host: email-smtp.ap-southeast-1.amazonaws.com
    Port: 2587
    Username: transactional-user
    Password: transactional-secret
    FromEmail: notify@notifications.bunnybooker.com
    FromName: BunnyBooker Notifications
    EnableSsl: true
    UseDefaultCredentials: false
    Timeout: 5000

Database:
  MAIN:
    AutoMigrate: false

Cache:
  MAIN:
    SSL: true
  STREAM:
    SSL: false
# external
HttpClient: {}
Auth:
  Settings:
    Issuer: https://api.descope.com/P2Z1Hu1nQxO8Ak5gdWFCtYXdHzZp
    Audience: P2Z1Hu1nQxO8Ak5gdWFCtYXdHzZp
    Domain: api.descope.com/P2Z1Hu1nQxO8Ak5gdWFCtYXdHzZp
