$schema: ./schema.json
# Native
App:
  Landscape: pichu
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Pichu Nitroso Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: true
Trace:
  Exporter:
    Otlp:
      Enabled: true

Metrics:
  Exporter:
    Otlp:
      Enabled: true

# Infra-based
Database:
  MAIN:
    AutoMigrate: false

Cache:
  MAIN:
    SSL: true

# external
HttpClient: {}
Auth:
  Settings:
    Issuer: P2Ya3WPmBmUBwJzhWoVB5uNeK7gg
    Audience: P2Ya3WPmBmUBwJzhWoVB5uNeK7gg
    Domain: api.descope.com/P2Ya3WPmBmUBwJzhWoVB5uNeK7gg
